# Generated by Django 5.0.2 on 2024-02-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='progress',
            field=models.CharField(blank=True, choices=[('Not started', 'Not started'), ('In progress', 'In progress'), ('Completed', 'Completed')], max_length=20, null=True),
        ),
    ]
